# Trabalhando com Planilhas do Excel

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel('Aracaju.xlsx')
df2 = pd.read_excel('Fortaleza.xlsx')
df3 = pd.read_excel('Natal.xlsx')
df4 = pd.read_excel('Recife.xlsx')
df5 = pd.read_excel('Salvador.xlsx')

In [4]:
df1.head()

    Cidade       Data  Vendas  LojaID  Qtde
0  Aracaju 2018-01-01  142.00    1520     1
1  Aracaju 2018-01-01   14.21    1522     6
2  Aracaju 2018-01-01   71.55    1520     1
3  Aracaju 2018-01-01    3.01    1521     7
4  Aracaju 2018-01-01   24.51    1522     8

In [5]:
df = pd.concat([df1, df2, df3, df4, df5])

In [6]:
df.count()

Cidade    894
Data      894
Vendas    894
LojaID    894
Qtde      894
dtype: int64

In [7]:
df.head()

    Cidade       Data  Vendas  LojaID  Qtde
0  Aracaju 2018-01-01  142.00    1520     1
1  Aracaju 2018-01-01   14.21    1522     6
2  Aracaju 2018-01-01   71.55    1520     1
3  Aracaju 2018-01-01    3.01    1521     7
4  Aracaju 2018-01-01   24.51    1522     8

In [12]:
df.head(894)

       Cidade       Data  Vendas  LojaID  Qtde
0     Aracaju 2018-01-01  142.00    1520     1
1     Aracaju 2018-01-01   14.21    1522     6
2     Aracaju 2018-01-01   71.55    1520     1
3     Aracaju 2018-01-01    3.01    1521     7
4     Aracaju 2018-01-01   24.51    1522     8
..        ...        ...     ...     ...   ...
235  Salvador 2019-01-03   41.84    1034     1
236  Salvador 2019-01-03  126.29    1035     3
237  Salvador 2019-01-03   38.06    1036     3
238  Salvador 2019-01-03  139.64    1035     1
239  Salvador 2019-01-03  161.41    1037     3

[894 rows x 5 columns]

In [13]:
df.sample(5)

       Cidade       Data  Vendas  LojaID  Qtde
79  Fortaleza 2019-01-01   41.25    1005     6
38     Recife 2019-01-01  104.53     983     4
12      Natal 2019-02-02  709.00     853     3
29   Salvador 2019-01-01    9.27    1034     1
83      Natal 2019-01-02   63.66    1036     2

In [14]:
df.sample(5)

       Cidade       Data  Vendas  LojaID  Qtde
91    Aracaju 2018-01-01  200.85    1522     6
133    Recife 2019-03-02   14.67     980     7
13     Recife 2019-02-12   15.33     983     5
64     Recife 2019-01-01   89.32     983     2
109  Salvador 2019-03-02  124.37    1035     1

In [15]:
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID             int64
Qtde               int64
dtype: object

In [16]:
df['LojaID'] = df['LojaID'].astype('object')

In [17]:
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID            object
Qtde               int64
dtype: object

tratando valores faltantes

In [18]:
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [19]:
df['Vendas'].mean()

122.61180089485438

In [20]:
df['Vendas'].fillna(df['Vendas'].mean(), inplace=True)

In [21]:
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [23]:
df.sample(15)

        Cidade       Data  Vendas LojaID  Qtde
20    Salvador 2019-01-01   33.97   1034     3
22    Salvador 2019-01-01   32.57   1035     1
70   Fortaleza 2019-01-01   79.57   1002     5
2    Fortaleza 2019-02-10   35.33   1004     3
11      Recife 2019-01-01  202.79    980     5
88    Salvador 2019-01-01   31.20   1036     1
73     Aracaju 2018-01-01  159.78   1521     3
213      Natal 2019-01-02   42.12   1035     1
120  Fortaleza 2019-03-02  184.90    982     4
64   Fortaleza 2019-01-01  110.31   1005     4
181      Natal 2019-01-02  244.83   1037     2
103   Salvador 2019-01-01  191.60   1034     1
134  Fortaleza 2019-03-02  195.18    980     5
197      Natal 2019-01-02   10.45   1036     2
34     Aracaju 2018-01-01   38.25   1521     6

In [24]:
df['Vendas'].fillna(0, inplace=True)

In [25]:
df.dropna(subset=['Vendas'], inplace=True)

In [26]:
df.dropna(how='all', inplace=True)

In [28]:
df.sample(5)

      Cidade       Data  Vendas LojaID  Qtde
4     Recife 2019-02-14   19.89    983     7
147    Natal 2019-01-02   34.50   1035     1
82    Recife 2019-01-01   29.55    981     6
86    Recife 2019-01-01   17.83    982     8
122  Aracaju 2018-01-01   38.49   1522     4

criando colunas novas

In [29]:
df['Receita'] = df['Vendas'].mul(df['Qtde'])

In [30]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita
0  Aracaju 2018-01-01  142.00   1520     1   142.00
1  Aracaju 2018-01-01   14.21   1522     6    85.26
2  Aracaju 2018-01-01   71.55   1520     1    71.55
3  Aracaju 2018-01-01    3.01   1521     7    21.07
4  Aracaju 2018-01-01   24.51   1522     8   196.08

In [31]:
df['Receita/Vendas'] = df['Receita'] / df['Vendas']

In [32]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
0  Aracaju 2018-01-01  142.00   1520     1   142.00             1.0
1  Aracaju 2018-01-01   14.21   1522     6    85.26             6.0
2  Aracaju 2018-01-01   71.55   1520     1    71.55             1.0
3  Aracaju 2018-01-01    3.01   1521     7    21.07             7.0
4  Aracaju 2018-01-01   24.51   1522     8   196.08             8.0

In [33]:
df['Receita'].max()

3544.0

In [34]:
df['Receita'].min()

3.34

In [35]:
df.nlargest(3, 'Receita')

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0

In [36]:
df.nsmallest(3, 'Receita')

      Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
118  Aracaju 2018-01-01    3.34   1522     1     3.34             1.0
65    Recife 2019-01-01    4.01    981     1     4.01             1.0
92     Natal 2019-01-02    4.57   1035     1     4.57             1.0

In [37]:
df.groupby('Cidade')['Receita'].sum()

Cidade
Aracaju       48748.25
Fortaleza     37913.97
Natal        167227.52
Recife        51936.51
Salvador      40596.73
Name: Receita, dtype: float64

In [38]:
df.sort_values('Receita', ascending=False).head(10)

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
30  Natal 2018-10-02   856.0    853     4   3424.0             4.0
41  Natal 2018-05-20   835.0    852     4   3340.0             4.0
38  Natal 2018-02-25   828.0    852     4   3312.0             4.0
10  Natal 2018-10-27   828.0    852     4   3312.0             4.0
69  Natal 2019-03-24   817.0    852     4   3268.0             4.0
62  Natal 2018-02-10   793.0    854     4   3172.0             4.0
52  Natal 2018-04-27   778.0    854     4   3112.0             4.0